// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxRlSjnlyE8gRbAJClw-Blcgp0TbRDlKc',
    appId: '1:209833452259:android:0d574e89ad037bfd07dbd6',
    messagingSenderId: '209833452259',
    projectId: 'e-com-f656d',
    storageBucket: 'e-com-f656d.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwFfoIkFqwuHDgKXxzEeaFJD-VQnHFd04',
    appId: '1:209833452259:web:038963d7b5ccfb1407dbd6',
    messagingSenderId: '209833452259',
    projectId: 'e-com-f656d',
    authDomain: 'e-com-f656d.firebaseapp.com',
    storageBucket: 'e-com-f656d.firebasestorage.app',
    measurementId: 'G-M6L7N592QY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpRAbX23cG5DzfbtYK2PeMXDaARcCx3WE',
    appId: '1:209833452259:ios:b667dbcbd7e484fc07dbd6',
    messagingSenderId: '209833452259',
    projectId: 'e-com-f656d',
    storageBucket: 'e-com-f656d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpRAbX23cG5DzfbtYK2PeMXDaARcCx3WE',
    appId: '1:209833452259:ios:b667dbcbd7e484fc07dbd6',
    messagingSenderId: '209833452259',
    projectId: 'e-com-f656d',
    storageBucket: 'e-com-f656d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwFfoIkFqwuHDgKXxzEeaFJD-VQnHFd04',
    appId: '1:209833452259:web:a9446d22045ab5fa07dbd6',
    messagingSenderId: '209833452259',
    projectId: 'e-com-f656d',
    authDomain: 'e-com-f656d.firebaseapp.com',
    storageBucket: 'e-com-f656d.firebasestorage.app',
    measurementId: 'G-J0F9XQTKSB',
  );

}